In [2]:
import pandas as pd

In [3]:
pd.read_csv('..\data\data-june12.csv')

       table_id                                    field_full_name
0   B19301Ae1    PER CAPITA INCOME IN THE PAST 12 MONTHS (IN 20...
1   B19301Am1    PER CAPITA INCOME IN THE PAST 12 MONTHS (IN 20...
2   B19301Be1    PER CAPITA INCOME IN THE PAST 12 MONTHS (IN 20...
3   B19301Bm1    PER CAPITA INCOME IN THE PAST 12 MONTHS (IN 20...
4   B19301Ce1    PER CAPITA INCOME IN THE PAST 12 MONTHS (IN 20...
5   B19301Cm1    PER CAPITA INCOME IN THE PAST 12 MONTHS (IN 20...
6   B19301De1    PER CAPITA INCOME IN THE PAST 12 MONTHS (IN 20...
7   B19301Dm1    PER CAPITA INCOME IN THE PAST 12 MONTHS (IN 20...
8   B19301e1     PER CAPITA INCOME IN THE PAST 12 MONTHS (IN 20...
9   B19301Ee1    PER CAPITA INCOME IN THE PAST 12 MONTHS (IN 20...
10  B19301Em1    PER CAPITA INCOME IN THE PAST 12 MONTHS (IN 20...
11  B19301Fe1    PER CAPITA INCOME IN THE PAST 12 MONTHS (IN 20...
12  B19301Fm1    PER CAPITA INCOME IN THE PAST 12 MONTHS (IN 20...
13  B19301Ge1    PER CAPITA INCOME IN THE PAST 12 MONTHS (IN 20...
14  B19301Gm1    PER CAPITA INCOME IN THE PAST 12 MONTHS (IN 20...
15  B19301He1    PER CAPITA INCOME IN THE PAST 12 MONTHS (IN 20...
16  B19301Hm1    PER CAPITA INCOME IN THE PAST 12 MONTHS (IN 20...
17  B19301Ie1    PER CAPITA INCOME IN THE PAST 12 MONTHS (IN 20...
18  B19301Im1    PER CAPITA INCOME IN THE PAST 12 MONTHS (IN 20...
19  B19301m1     PER CAPITA INCOME IN THE PAST 12 MONTHS (IN 20...